// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: announcements.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (owner_id, property_id, title, body, send_email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, property_id, title, body, send_email, created_at
`

type CreateAnnouncementParams struct {
	OwnerID    uuid.UUID     `json:"owner_id"`
	PropertyID uuid.NullUUID `json:"property_id"`
	Title      string        `json:"title"`
	Body       string        `json:"body"`
	SendEmail  sql.NullBool  `json:"send_email"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRowContext(ctx, createAnnouncement,
		arg.OwnerID,
		arg.PropertyID,
		arg.Title,
		arg.Body,
		arg.SendEmail,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PropertyID,
		&i.Title,
		&i.Body,
		&i.SendEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveTenantsByOwner = `-- name: GetActiveTenantsByOwner :many
SELECT t.id, p.full_name, p.email
FROM tenants t
JOIN profiles p ON p.id = t.id
JOIN properties pr ON pr.id = t.property_id
WHERE pr.owner_id = $1
  AND t.archived_at IS NULL
  AND pr.archived_at IS NULL
  AND (t.is_blacklisted IS NULL OR t.is_blacklisted = FALSE)
`

type GetActiveTenantsByOwnerRow struct {
	ID       uuid.UUID      `json:"id"`
	FullName string         `json:"full_name"`
	Email    sql.NullString `json:"email"`
}

func (q *Queries) GetActiveTenantsByOwner(ctx context.Context, ownerID uuid.UUID) ([]GetActiveTenantsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTenantsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveTenantsByOwnerRow{}
	for rows.Next() {
		var i GetActiveTenantsByOwnerRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTenantsByProperty = `-- name: GetActiveTenantsByProperty :many
SELECT t.id, p.full_name, p.email
FROM tenants t
JOIN profiles p ON p.id = t.id
WHERE t.property_id = $1
  AND t.archived_at IS NULL
  AND (t.is_blacklisted IS NULL OR t.is_blacklisted = FALSE)
`

type GetActiveTenantsByPropertyRow struct {
	ID       uuid.UUID      `json:"id"`
	FullName string         `json:"full_name"`
	Email    sql.NullString `json:"email"`
}

func (q *Queries) GetActiveTenantsByProperty(ctx context.Context, propertyID uuid.NullUUID) ([]GetActiveTenantsByPropertyRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTenantsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveTenantsByPropertyRow{}
	for rows.Next() {
		var i GetActiveTenantsByPropertyRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, owner_id, property_id, title, body, send_email, created_at
FROM announcements
WHERE owner_id = $1
  AND ($2::uuid IS NULL OR property_id = $2)
ORDER BY created_at DESC
`

type ListAnnouncementsParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements, arg.OwnerID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.PropertyID,
			&i.Title,
			&i.Body,
			&i.SendEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
