// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: announcements.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (owner_id, property_id, title, body, send_email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, property_id, title, body, send_email, created_at
`

type CreateAnnouncementParams struct {
	OwnerID    uuid.UUID     `json:"owner_id"`
	PropertyID uuid.NullUUID `json:"property_id"`
	Title      string        `json:"title"`
	Body       string        `json:"body"`
	SendEmail  sql.NullBool  `json:"send_email"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRowContext(ctx, createAnnouncement,
		arg.OwnerID,
		arg.PropertyID,
		arg.Title,
		arg.Body,
		arg.SendEmail,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PropertyID,
		&i.Title,
		&i.Body,
		&i.SendEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, owner_id, property_id, title, body, send_email, created_at
FROM announcements
WHERE owner_id = $1
  AND ($2::uuid IS NULL OR property_id = $2)
ORDER BY created_at DESC
`

type ListAnnouncementsParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements, arg.OwnerID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.PropertyID,
			&i.Title,
			&i.Body,
			&i.SendEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
