// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor_id, action, entity_type, entity_id, metadata, created_at
`

type CreateAuditLogParams struct {
	ActorID    uuid.UUID       `json:"actor_id"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   interface{}     `json:"entity_id"`
	Metadata   json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, entity_type, entity_id, metadata, created_at
FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsParams struct {
	ActorID   interface{} `json:"actor_id"`
	Action    interface{} `json:"action"`
	FromTime  interface{} `json:"from_time"`
	ToTime    interface{} `json:"to_time"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.FromTime,
		arg.ToTime,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
