// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bills.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listBills = `-- name: ListBills :many
SELECT id, tenant_id, property_id, room_id, period_month, period_year,
       base_amount, utility_amount, penalty_amount, total_amount,
       due_date, status, created_at, updated_at
FROM bills
WHERE property_id = $1
ORDER BY period_year DESC, period_month DESC, created_at DESC
`

func (q *Queries) ListBills(ctx context.Context, propertyID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listBills, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.RoomID,
			&i.PeriodMonth,
			&i.PeriodYear,
			&i.BaseAmount,
			&i.UtilityAmount,
			&i.PenaltyAmount,
			&i.TotalAmount,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBill = `-- name: GetBill :one
SELECT id, tenant_id, property_id, room_id, period_month, period_year,
       base_amount, utility_amount, penalty_amount, total_amount,
       due_date, status, created_at, updated_at
FROM bills
WHERE id = $1
`

func (q *Queries) GetBill(ctx context.Context, id uuid.UUID) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBill, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.PeriodMonth,
		&i.PeriodYear,
		&i.BaseAmount,
		&i.UtilityAmount,
		&i.PenaltyAmount,
		&i.TotalAmount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBill = `-- name: CreateBill :one
INSERT INTO bills (tenant_id, property_id, room_id, period_month, period_year, base_amount, utility_amount, penalty_amount, due_date, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, property_id, room_id, period_month, period_year, base_amount, utility_amount, penalty_amount, total_amount, due_date, status, created_at, updated_at
`

// CreateBillParams — note: total_amount is a GENERATED column and is excluded from INSERT.
type CreateBillParams struct {
	TenantID      uuid.UUID   `json:"tenant_id"`
	PropertyID    uuid.UUID   `json:"property_id"`
	RoomID        uuid.UUID   `json:"room_id"`
	PeriodMonth   int32       `json:"period_month"`
	PeriodYear    int32       `json:"period_year"`
	BaseAmount    string      `json:"base_amount"`
	UtilityAmount interface{} `json:"utility_amount"`
	PenaltyAmount interface{} `json:"penalty_amount"`
	DueDate       time.Time   `json:"due_date"`
	Status        string      `json:"status"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill,
		arg.TenantID,
		arg.PropertyID,
		arg.RoomID,
		arg.PeriodMonth,
		arg.PeriodYear,
		arg.BaseAmount,
		arg.UtilityAmount,
		arg.PenaltyAmount,
		arg.DueDate,
		arg.Status,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.PeriodMonth,
		&i.PeriodYear,
		&i.BaseAmount,
		&i.UtilityAmount,
		&i.PenaltyAmount,
		&i.TotalAmount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillStatus = `-- name: UpdateBillStatus :one
UPDATE bills
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, property_id, room_id, period_month, period_year, base_amount, utility_amount, penalty_amount, total_amount, due_date, status, created_at, updated_at
`

type UpdateBillStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, updateBillStatus, arg.ID, arg.Status)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.PeriodMonth,
		&i.PeriodYear,
		&i.BaseAmount,
		&i.UtilityAmount,
		&i.PenaltyAmount,
		&i.TotalAmount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillUtilityAmount = `-- name: UpdateBillUtilityAmount :one
UPDATE bills
SET utility_amount = $2,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, tenant_id, property_id, room_id, period_month, period_year, base_amount, utility_amount, penalty_amount, total_amount, due_date, status, created_at, updated_at
`

type UpdateBillUtilityAmountParams struct {
	ID            uuid.UUID `json:"id"`
	UtilityAmount string    `json:"utility_amount"`
}

func (q *Queries) UpdateBillUtilityAmount(ctx context.Context, arg UpdateBillUtilityAmountParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, updateBillUtilityAmount, arg.ID, arg.UtilityAmount)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.PeriodMonth,
		&i.PeriodYear,
		&i.BaseAmount,
		&i.UtilityAmount,
		&i.PenaltyAmount,
		&i.TotalAmount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillsByTenant = `-- name: ListBillsByTenant :many
SELECT id, tenant_id, property_id, room_id, period_month, period_year,
       base_amount, utility_amount, penalty_amount, total_amount,
       due_date, status, created_at, updated_at
FROM bills
WHERE tenant_id = $1
ORDER BY period_year DESC, period_month DESC
`

func (q *Queries) ListBillsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listBillsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.RoomID,
			&i.PeriodMonth,
			&i.PeriodYear,
			&i.BaseAmount,
			&i.UtilityAmount,
			&i.PenaltyAmount,
			&i.TotalAmount,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// GetFinancialReportRow is the return type for GetFinancialReport.
type GetFinancialReportRow struct {
	PropertyID  uuid.UUID `json:"property_id"`
	PeriodMonth int32     `json:"period_month"`
	PeriodYear  int32     `json:"period_year"`
	TotalBilled string    `json:"total_billed"`
	TotalPaid   string    `json:"total_paid"`
	BillCount   int64     `json:"bill_count"`
}

const getFinancialReport = `-- name: GetFinancialReport :many
SELECT b.property_id,
       b.period_month,
       b.period_year,
       SUM(b.total_amount)   AS total_billed,
       SUM(CASE WHEN b.status = 'paid' THEN b.total_amount ELSE 0 END) AS total_paid,
       COUNT(*)              AS bill_count
FROM bills b
WHERE b.property_id = $1
  AND (b.period_year > $2 OR (b.period_year = $2 AND b.period_month >= $3))
  AND (b.period_year < $4 OR (b.period_year = $4 AND b.period_month <= $5))
GROUP BY b.property_id, b.period_year, b.period_month
ORDER BY b.period_year ASC, b.period_month ASC
`

type GetFinancialReportParams struct {
	PropertyID  uuid.UUID `json:"property_id"`
	FromYear    int32     `json:"from_year"`
	FromMonth   int32     `json:"from_month"`
	ToYear      int32     `json:"to_year"`
	ToMonth     int32     `json:"to_month"`
}

func (q *Queries) GetFinancialReport(ctx context.Context, arg GetFinancialReportParams) ([]GetFinancialReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getFinancialReport,
		arg.PropertyID,
		arg.FromYear,
		arg.FromMonth,
		arg.ToYear,
		arg.ToMonth,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinancialReportRow
	for rows.Next() {
		var i GetFinancialReportRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.PeriodMonth,
			&i.PeriodYear,
			&i.TotalBilled,
			&i.TotalPaid,
			&i.BillCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
