// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contracts_expiring.sql

package repository

import (
	"context"
)

const listExpiringContractsWithinDays = `-- name: ListExpiringContractsWithinDays :many
SELECT
    c.id,
    c.tenant_id,
    c.room_id,
    c.property_id,
    c.start_date,
    c.end_date,
    c.monthly_price,
    c.deposit_amount,
    c.deposit_refunded,
    c.status,
    c.file_url,
    c.created_at,
    c.updated_at
FROM contracts c
WHERE c.status = 'active'
  AND c.end_date <= NOW() + make_interval(days => $1)
  AND c.end_date >= NOW()
ORDER BY c.end_date ASC
`

func (q *Queries) ListExpiringContractsWithinDays(ctx context.Context, days int32) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringContractsWithinDays, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contract{}
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.PropertyID,
			&i.StartDate,
			&i.EndDate,
			&i.MonthlyPrice,
			&i.DepositAmount,
			&i.DepositRefunded,
			&i.Status,
			&i.FileUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
