// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contract_templates.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const listContractTemplates = `-- name: ListContractTemplates :many
SELECT id, owner_id, name, content, created_at, updated_at
FROM contract_templates
WHERE owner_id = $1
ORDER BY name ASC
`

func (q *Queries) ListContractTemplates(ctx context.Context, ownerID uuid.UUID) ([]ContractTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listContractTemplates, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContractTemplate
	for rows.Next() {
		var i ContractTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContractTemplate = `-- name: GetContractTemplate :one
SELECT id, owner_id, name, content, created_at, updated_at
FROM contract_templates
WHERE id = $1
`

func (q *Queries) GetContractTemplate(ctx context.Context, id uuid.UUID) (ContractTemplate, error) {
	row := q.db.QueryRowContext(ctx, getContractTemplate, id)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContractTemplate = `-- name: CreateContractTemplate :one
INSERT INTO contract_templates (owner_id, name, content)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, content, created_at, updated_at
`

type CreateContractTemplateParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
	Content string    `json:"content"`
}

func (q *Queries) CreateContractTemplate(ctx context.Context, arg CreateContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRowContext(ctx, createContractTemplate,
		arg.OwnerID,
		arg.Name,
		arg.Content,
	)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContractTemplate = `-- name: UpdateContractTemplate :one
UPDATE contract_templates
SET name       = $2,
    content    = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, content, created_at, updated_at
`

type UpdateContractTemplateParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateContractTemplate(ctx context.Context, arg UpdateContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateContractTemplate,
		arg.ID,
		arg.Name,
		arg.Content,
	)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
