// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invitations.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (owner_id, property_id, email, token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, property_id, email, token, expires_at, used_at, created_at
`

type CreateInvitationParams struct {
	OwnerID    uuid.UUID     `json:"owner_id"`
	PropertyID uuid.NullUUID `json:"property_id"`
	Email      string        `json:"email"`
	Token      string        `json:"token"`
	ExpiresAt  time.Time     `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.OwnerID,
		arg.PropertyID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PropertyID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, owner_id, property_id, email, token, expires_at, used_at, created_at
FROM invitations
WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PropertyID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markInvitationUsed = `-- name: MarkInvitationUsed :one
UPDATE invitations
SET used_at = NOW()
WHERE id = $1
RETURNING id, owner_id, property_id, email, token, expires_at, used_at, created_at
`

func (q *Queries) MarkInvitationUsed(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, markInvitationUsed, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PropertyID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
