// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const listConversations = `-- name: ListConversations :many
SELECT DISTINCT ON (LEAST(sender_id, receiver_id), GREATEST(sender_id, receiver_id))
       id, sender_id, receiver_id, property_id, body, is_read, created_at
FROM messages
WHERE sender_id = $1
   OR receiver_id = $1
ORDER BY LEAST(sender_id, receiver_id),
         GREATEST(sender_id, receiver_id),
         created_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, userID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.PropertyID,
			&i.Body,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageThread = `-- name: GetMessageThread :many
SELECT id, sender_id, receiver_id, property_id, body, is_read, created_at
FROM messages
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
ORDER BY created_at ASC
`

type GetMessageThreadParams struct {
	UserA uuid.UUID `json:"user_a"`
	UserB uuid.UUID `json:"user_b"`
}

func (q *Queries) GetMessageThread(ctx context.Context, arg GetMessageThreadParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessageThread, arg.UserA, arg.UserB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.PropertyID,
			&i.Body,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, receiver_id, property_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, sender_id, receiver_id, property_id, body, is_read, created_at
`

type CreateMessageParams struct {
	SenderID   uuid.UUID   `json:"sender_id"`
	ReceiverID uuid.UUID   `json:"receiver_id"`
	PropertyID interface{} `json:"property_id"`
	Body       string      `json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.SenderID,
		arg.ReceiverID,
		arg.PropertyID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.PropertyID,
		&i.Body,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadMessages = `-- name: GetUnreadMessages :many
SELECT id, sender_id, receiver_id, property_id, body, is_read, created_at
FROM messages
WHERE receiver_id = $1
  AND is_read = FALSE
ORDER BY created_at DESC
`

func (q *Queries) GetUnreadMessages(ctx context.Context, receiverID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadMessages, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.PropertyID,
			&i.Body,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
