// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Profile represents a row from the profiles table.
type Profile struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Phone     sql.NullString `json:"phone"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

// Property represents a row from the properties table.
type Property struct {
	ID          uuid.UUID      `json:"id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// RoomType represents a row from the room_types table.
type RoomType struct {
	ID           uuid.UUID `json:"id"`
	PropertyID   uuid.UUID `json:"property_id"`
	Name         string    `json:"name"`
	MonthlyPrice string    `json:"monthly_price"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

// Room represents a row from the rooms table.
type Room struct {
	ID           uuid.UUID       `json:"id"`
	PropertyID   uuid.UUID       `json:"property_id"`
	RoomTypeID   uuid.NullUUID   `json:"room_type_id"`
	Number       string          `json:"number"`
	Floor        sql.NullInt32   `json:"floor"`
	Status       string          `json:"status"`
	GridX        sql.NullInt32   `json:"grid_x"`
	GridY        sql.NullInt32   `json:"grid_y"`
	Facilities   json.RawMessage `json:"facilities"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

// RoomPhoto represents a row from the room_photos table.
type RoomPhoto struct {
	ID        uuid.UUID    `json:"id"`
	RoomID    uuid.UUID    `json:"room_id"`
	Url       string       `json:"url"`
	OrderIdx  sql.NullInt32 `json:"order_idx"`
	CreatedAt sql.NullTime `json:"created_at"`
}

// Tenant represents a row from the tenants table.
type Tenant struct {
	ID              uuid.UUID      `json:"id"`
	PropertyID      uuid.NullUUID  `json:"property_id"`
	RoomID          uuid.NullUUID  `json:"room_id"`
	KtpNumber       sql.NullString `json:"ktp_number"`
	KtpScanUrl      sql.NullString `json:"ktp_scan_url"`
	Occupation      sql.NullString `json:"occupation"`
	EmergencyName   sql.NullString `json:"emergency_name"`
	EmergencyPhone  sql.NullString `json:"emergency_phone"`
	IsBlacklisted   sql.NullBool   `json:"is_blacklisted"`
	BlacklistReason sql.NullString `json:"blacklist_reason"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

// Contract represents a row from the contracts table.
type Contract struct {
	ID               uuid.UUID      `json:"id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	RoomID           uuid.UUID      `json:"room_id"`
	PropertyID       uuid.UUID      `json:"property_id"`
	StartDate        time.Time      `json:"start_date"`
	EndDate          time.Time      `json:"end_date"`
	MonthlyPrice     string         `json:"monthly_price"`
	DepositAmount    sql.NullString `json:"deposit_amount"`
	DepositRefunded  sql.NullString `json:"deposit_refunded"`
	Status           string         `json:"status"`
	FileUrl          sql.NullString `json:"file_url"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

// Bill represents a row from the bills table.
type Bill struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	PropertyID    uuid.UUID      `json:"property_id"`
	RoomID        uuid.UUID      `json:"room_id"`
	PeriodMonth   int32          `json:"period_month"`
	PeriodYear    int32          `json:"period_year"`
	BaseAmount    string         `json:"base_amount"`
	UtilityAmount sql.NullString `json:"utility_amount"`
	PenaltyAmount sql.NullString `json:"penalty_amount"`
	TotalAmount   sql.NullString `json:"total_amount"` // GENERATED column — read-only
	DueDate       time.Time      `json:"due_date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

// UtilityCharge represents a row from the utility_charges table.
type UtilityCharge struct {
	ID        uuid.UUID      `json:"id"`
	BillID    uuid.UUID      `json:"bill_id"`
	Type      string         `json:"type"`
	Amount    string         `json:"amount"`
	Note      sql.NullString `json:"note"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// Payment represents a row from the payments table.
type Payment struct {
	ID              uuid.UUID      `json:"id"`
	BillID          uuid.UUID      `json:"bill_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	Amount          string         `json:"amount"`
	ProofUrl        sql.NullString `json:"proof_url"`
	Status          string         `json:"status"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	ConfirmedBy     uuid.NullUUID  `json:"confirmed_by"`
	ConfirmedAt     sql.NullTime   `json:"confirmed_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

// Ticket represents a row from the tickets table.
type Ticket struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	PropertyID  uuid.UUID      `json:"property_id"`
	RoomID      uuid.NullUUID  `json:"room_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Priority    string         `json:"priority"`
	Status      string         `json:"status"`
	Resolution  sql.NullString `json:"resolution"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// TicketAttachment represents a row from the ticket_attachments table.
type TicketAttachment struct {
	ID        uuid.UUID    `json:"id"`
	TicketID  uuid.UUID    `json:"ticket_id"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
}

// Notification represents a row from the notifications table.
type Notification struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	EntityID  uuid.NullUUID  `json:"entity_id"`
	IsRead    sql.NullBool   `json:"is_read"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// AuditLog represents a row from the audit_logs table.
type AuditLog struct {
	ID         uuid.UUID       `json:"id"`
	ActorID    uuid.UUID       `json:"actor_id"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   uuid.NullUUID   `json:"entity_id"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}

// Invitation represents a row from the invitations table.
type Invitation struct {
	ID         uuid.UUID     `json:"id"`
	OwnerID    uuid.UUID     `json:"owner_id"`
	PropertyID uuid.NullUUID `json:"property_id"`
	Email      string        `json:"email"`
	Token      string        `json:"token"`
	ExpiresAt  time.Time     `json:"expires_at"`
	UsedAt     sql.NullTime  `json:"used_at"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

// Message represents a row from the messages table.
type Message struct {
	ID         uuid.UUID     `json:"id"`
	SenderID   uuid.UUID     `json:"sender_id"`
	ReceiverID uuid.UUID     `json:"receiver_id"`
	PropertyID uuid.NullUUID `json:"property_id"`
	Body       string        `json:"body"`
	IsRead     sql.NullBool  `json:"is_read"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

// Announcement represents a row from the announcements table.
type Announcement struct {
	ID         uuid.UUID     `json:"id"`
	OwnerID    uuid.UUID     `json:"owner_id"`
	PropertyID uuid.NullUUID `json:"property_id"`
	Title      string        `json:"title"`
	Body       string        `json:"body"`
	SendEmail  sql.NullBool  `json:"send_email"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

// ContractTemplate represents a row from the contract_templates table.
type ContractTemplate struct {
	ID        uuid.UUID    `json:"id"`
	OwnerID   uuid.UUID    `json:"owner_id"`
	Name      string       `json:"name"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// StaffPermission represents a row from the staff_permissions table.
type StaffPermission struct {
	ID        uuid.UUID       `json:"id"`
	StaffID   uuid.UUID       `json:"staff_id"`
	OwnerID   uuid.UUID       `json:"owner_id"`
	Modules   json.RawMessage `json:"modules"`
	CreatedAt sql.NullTime    `json:"created_at"`
}
