// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, entity_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, entity_id, is_read, created_at
`

type CreateNotificationParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	Type     string         `json:"type"`
	Title    string         `json:"title"`
	Body     sql.NullString `json:"body"`
	EntityID uuid.NullUUID  `json:"entity_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.EntityID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.EntityID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, entity_id, is_read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.EntityID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
  AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
