// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (bill_id, tenant_id, amount, proof_url, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bill_id, tenant_id, amount, proof_url, status, rejection_reason, confirmed_by, confirmed_at, created_at
`

type CreatePaymentParams struct {
	BillID   uuid.UUID   `json:"bill_id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	Amount   string      `json:"amount"`
	ProofUrl interface{} `json:"proof_url"`
	Status   string      `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.BillID,
		arg.TenantID,
		arg.Amount,
		arg.ProofUrl,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.TenantID,
		&i.Amount,
		&i.ProofUrl,
		&i.Status,
		&i.RejectionReason,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, bill_id, tenant_id, amount, proof_url, status, rejection_reason, confirmed_by, confirmed_at, created_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.TenantID,
		&i.Amount,
		&i.ProofUrl,
		&i.Status,
		&i.RejectionReason,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status           = $2,
    rejection_reason = $3,
    confirmed_by     = $4,
    confirmed_at     = $5
WHERE id = $1
RETURNING id, bill_id, tenant_id, amount, proof_url, status, rejection_reason, confirmed_by, confirmed_at, created_at
`

type UpdatePaymentStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          string      `json:"status"`
	RejectionReason interface{} `json:"rejection_reason"`
	ConfirmedBy     interface{} `json:"confirmed_by"`
	ConfirmedAt     interface{} `json:"confirmed_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.ConfirmedBy,
		arg.ConfirmedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.TenantID,
		&i.Amount,
		&i.ProofUrl,
		&i.Status,
		&i.RejectionReason,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByBill = `-- name: ListPaymentsByBill :many
SELECT id, bill_id, tenant_id, amount, proof_url, status, rejection_reason, confirmed_by, confirmed_at, created_at
FROM payments
WHERE bill_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByBill(ctx context.Context, billID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByBill, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.TenantID,
			&i.Amount,
			&i.ProofUrl,
			&i.Status,
			&i.RejectionReason,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
