// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profiles.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, full_name, avatar_url, phone, role, created_at, updated_at
FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET full_name  = $2,
    avatar_url = $3,
    phone      = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, avatar_url, phone, role, created_at, updated_at
`

type UpdateProfileParams struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Phone     sql.NullString `json:"phone"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.ID,
		arg.FullName,
		arg.AvatarUrl,
		arg.Phone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (id, full_name, avatar_url, phone, role)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
  SET full_name  = EXCLUDED.full_name,
      avatar_url = EXCLUDED.avatar_url,
      phone      = EXCLUDED.phone,
      updated_at = NOW()
RETURNING id, full_name, avatar_url, phone, role, created_at, updated_at
`

type UpsertProfileParams struct {
	ID        uuid.UUID      `json:"id"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Phone     sql.NullString `json:"phone"`
	Role      string         `json:"role"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, upsertProfile,
		arg.ID,
		arg.FullName,
		arg.AvatarUrl,
		arg.Phone,
		arg.Role,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
