// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: properties.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const archiveProperty = `-- name: ArchiveProperty :exec
UPDATE properties SET archived_at = NOW() WHERE id = $1
`

func (q *Queries) ArchiveProperty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveProperty, id)
	return err
}

const archiveRoomsByProperty = `-- name: ArchiveRoomsByProperty :exec
UPDATE rooms SET archived_at = NOW() WHERE property_id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveRoomsByProperty(ctx context.Context, propertyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveRoomsByProperty, propertyID)
	return err
}

const archiveTenantsByProperty = `-- name: ArchiveTenantsByProperty :exec
UPDATE tenants SET archived_at = NOW() WHERE property_id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveTenantsByProperty(ctx context.Context, propertyID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, archiveTenantsByProperty, propertyID)
	return err
}

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (owner_id, name, address, city, logo_url, phone, bank_name, bank_account)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account, created_at, updated_at
`

type CreatePropertyParams struct {
	OwnerID     uuid.UUID      `json:"owner_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
}

type CreatePropertyRow struct {
	ID          uuid.UUID      `json:"id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (CreatePropertyRow, error) {
	row := q.db.QueryRowContext(ctx, createProperty,
		arg.OwnerID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.LogoUrl,
		arg.Phone,
		arg.BankName,
		arg.BankAccount,
	)
	var i CreatePropertyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProperty = `-- name: DeleteProperty :exec
DELETE FROM properties WHERE id = $1
`

func (q *Queries) DeleteProperty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProperty, id)
	return err
}

const getProperty = `-- name: GetProperty :one
SELECT id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account, created_at, updated_at
FROM properties
WHERE id = $1
  AND archived_at IS NULL
`

type GetPropertyRow struct {
	ID          uuid.UUID      `json:"id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetProperty(ctx context.Context, id uuid.UUID) (GetPropertyRow, error) {
	row := q.db.QueryRowContext(ctx, getProperty, id)
	var i GetPropertyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPropertyWithStats = `-- name: GetPropertyWithStats :one
SELECT
  p.id,
  p.owner_id,
  p.name,
  p.address,
  p.city,
  p.logo_url,
  p.phone,
  p.bank_name,
  p.bank_account,
  p.created_at,
  p.updated_at,
  COUNT(r.id)                                                    AS total_rooms,
  COUNT(r.id) FILTER (WHERE r.status = 'occupied')              AS occupied_rooms
FROM properties p
LEFT JOIN rooms r ON r.property_id = p.id AND r.archived_at IS NULL
WHERE p.id = $1
  AND p.archived_at IS NULL
GROUP BY p.id
`

type GetPropertyWithStatsRow struct {
	ID            uuid.UUID      `json:"id"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	Name          string         `json:"name"`
	Address       string         `json:"address"`
	City          sql.NullString `json:"city"`
	LogoUrl       sql.NullString `json:"logo_url"`
	Phone         sql.NullString `json:"phone"`
	BankName      sql.NullString `json:"bank_name"`
	BankAccount   sql.NullString `json:"bank_account"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	TotalRooms    int64          `json:"total_rooms"`
	OccupiedRooms int64          `json:"occupied_rooms"`
}

func (q *Queries) GetPropertyWithStats(ctx context.Context, id uuid.UUID) (GetPropertyWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPropertyWithStats, id)
	var i GetPropertyWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalRooms,
		&i.OccupiedRooms,
	)
	return i, err
}

const listPropertiesByOwner = `-- name: ListPropertiesByOwner :many
SELECT id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account, created_at, updated_at
FROM properties
WHERE owner_id = $1
  AND archived_at IS NULL
ORDER BY created_at DESC
`

type ListPropertiesByOwnerRow struct {
	ID          uuid.UUID      `json:"id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListPropertiesByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListPropertiesByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesByOwnerRow{}
	for rows.Next() {
		var i ListPropertiesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.LogoUrl,
			&i.Phone,
			&i.BankName,
			&i.BankAccount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesWithStatsByOwner = `-- name: ListPropertiesWithStatsByOwner :many
SELECT
  p.id,
  p.owner_id,
  p.name,
  p.address,
  p.city,
  p.logo_url,
  p.phone,
  p.bank_name,
  p.bank_account,
  p.created_at,
  p.updated_at,
  COUNT(r.id)                                                    AS total_rooms,
  COUNT(r.id) FILTER (WHERE r.status = 'occupied')              AS occupied_rooms
FROM properties p
LEFT JOIN rooms r ON r.property_id = p.id AND r.archived_at IS NULL
WHERE p.owner_id = $1
  AND p.archived_at IS NULL
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPropertiesWithStatsByOwnerRow struct {
	ID            uuid.UUID      `json:"id"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	Name          string         `json:"name"`
	Address       string         `json:"address"`
	City          sql.NullString `json:"city"`
	LogoUrl       sql.NullString `json:"logo_url"`
	Phone         sql.NullString `json:"phone"`
	BankName      sql.NullString `json:"bank_name"`
	BankAccount   sql.NullString `json:"bank_account"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	TotalRooms    int64          `json:"total_rooms"`
	OccupiedRooms int64          `json:"occupied_rooms"`
}

func (q *Queries) ListPropertiesWithStatsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListPropertiesWithStatsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesWithStatsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesWithStatsByOwnerRow{}
	for rows.Next() {
		var i ListPropertiesWithStatsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.LogoUrl,
			&i.Phone,
			&i.BankName,
			&i.BankAccount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalRooms,
			&i.OccupiedRooms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties
SET name         = $2,
    address      = $3,
    city         = $4,
    logo_url     = $5,
    phone        = $6,
    bank_name    = $7,
    bank_account = $8,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account, created_at, updated_at
`

type UpdatePropertyParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
}

type UpdatePropertyRow struct {
	ID          uuid.UUID      `json:"id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (UpdatePropertyRow, error) {
	row := q.db.QueryRowContext(ctx, updateProperty,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.LogoUrl,
		arg.Phone,
		arg.BankName,
		arg.BankAccount,
	)
	var i UpdatePropertyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
