// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room_photos.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRoomPhoto = `-- name: CreateRoomPhoto :one
INSERT INTO room_photos (room_id, url, order_idx)
VALUES ($1, $2, $3)
RETURNING id, room_id, url, order_idx, created_at
`

type CreateRoomPhotoParams struct {
	RoomID   uuid.UUID     `json:"room_id"`
	Url      string        `json:"url"`
	OrderIdx sql.NullInt32 `json:"order_idx"`
}

func (q *Queries) CreateRoomPhoto(ctx context.Context, arg CreateRoomPhotoParams) (RoomPhoto, error) {
	row := q.db.QueryRowContext(ctx, createRoomPhoto, arg.RoomID, arg.Url, arg.OrderIdx)
	var i RoomPhoto
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Url,
		&i.OrderIdx,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoomPhoto = `-- name: DeleteRoomPhoto :exec
DELETE FROM room_photos WHERE id = $1
`

func (q *Queries) DeleteRoomPhoto(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoomPhoto, id)
	return err
}

const getRoomPhoto = `-- name: GetRoomPhoto :one
SELECT id, room_id, url, order_idx, created_at
FROM room_photos
WHERE id = $1
`

func (q *Queries) GetRoomPhoto(ctx context.Context, id uuid.UUID) (RoomPhoto, error) {
	row := q.db.QueryRowContext(ctx, getRoomPhoto, id)
	var i RoomPhoto
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Url,
		&i.OrderIdx,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomPhotos = `-- name: ListRoomPhotos :many
SELECT id, room_id, url, order_idx, created_at
FROM room_photos
WHERE room_id = $1
ORDER BY order_idx ASC
`

func (q *Queries) ListRoomPhotos(ctx context.Context, roomID uuid.UUID) ([]RoomPhoto, error) {
	rows, err := q.db.QueryContext(ctx, listRoomPhotos, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPhoto{}
	for rows.Next() {
		var i RoomPhoto
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Url,
			&i.OrderIdx,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
