// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room_types.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const listRoomTypesByProperty = `-- name: ListRoomTypesByProperty :many
SELECT id, property_id, name, monthly_price, created_at
FROM room_types
WHERE property_id = $1
ORDER BY name ASC
`

func (q *Queries) ListRoomTypesByProperty(ctx context.Context, propertyID uuid.UUID) ([]RoomType, error) {
	rows, err := q.db.QueryContext(ctx, listRoomTypesByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomType
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.MonthlyPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomType = `-- name: GetRoomType :one
SELECT id, property_id, name, monthly_price, created_at
FROM room_types
WHERE id = $1
`

func (q *Queries) GetRoomType(ctx context.Context, id uuid.UUID) (RoomType, error) {
	row := q.db.QueryRowContext(ctx, getRoomType, id)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Name,
		&i.MonthlyPrice,
		&i.CreatedAt,
	)
	return i, err
}

const createRoomType = `-- name: CreateRoomType :one
INSERT INTO room_types (property_id, name, monthly_price)
VALUES ($1, $2, $3)
RETURNING id, property_id, name, monthly_price, created_at
`

type CreateRoomTypeParams struct {
	PropertyID   uuid.UUID `json:"property_id"`
	Name         string    `json:"name"`
	MonthlyPrice string    `json:"monthly_price"`
}

func (q *Queries) CreateRoomType(ctx context.Context, arg CreateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRowContext(ctx, createRoomType,
		arg.PropertyID,
		arg.Name,
		arg.MonthlyPrice,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Name,
		&i.MonthlyPrice,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoomType = `-- name: UpdateRoomType :one
UPDATE room_types
SET name          = $2,
    monthly_price = $3
WHERE id = $1
RETURNING id, property_id, name, monthly_price, created_at
`

type UpdateRoomTypeParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	MonthlyPrice string    `json:"monthly_price"`
}

func (q *Queries) UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRowContext(ctx, updateRoomType,
		arg.ID,
		arg.Name,
		arg.MonthlyPrice,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Name,
		&i.MonthlyPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomTypeByName = `-- name: GetRoomTypeByName :one
SELECT id, property_id, name, monthly_price, created_at
FROM room_types
WHERE property_id = $1 AND name = $2
LIMIT 1
`

type GetRoomTypeByNameParams struct {
	PropertyID uuid.UUID `json:"property_id"`
	Name       string    `json:"name"`
}

// GetRoomTypeByName returns a room type by property and name, or sql.ErrNoRows if not found.
func (q *Queries) GetRoomTypeByName(ctx context.Context, arg GetRoomTypeByNameParams) (RoomType, error) {
	row := q.db.QueryRowContext(ctx, getRoomTypeByName, arg.PropertyID, arg.Name)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Name,
		&i.MonthlyPrice,
		&i.CreatedAt,
	)
	return i, err
}
