// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const archiveRoom = `-- name: ArchiveRoom :exec
UPDATE rooms SET archived_at = NOW() WHERE id = $1
`

func (q *Queries) ArchiveRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveRoom, id)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (property_id, room_type_id, number, floor, status, grid_x, grid_y, facilities)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, property_id, room_type_id, number, floor, status, grid_x, grid_y, facilities, created_at, updated_at
`

type CreateRoomParams struct {
	PropertyID uuid.UUID             `json:"property_id"`
	RoomTypeID uuid.NullUUID         `json:"room_type_id"`
	Number     string                `json:"number"`
	Floor      sql.NullInt32         `json:"floor"`
	Status     string                `json:"status"`
	GridX      sql.NullInt32         `json:"grid_x"`
	GridY      sql.NullInt32         `json:"grid_y"`
	Facilities pqtype.NullRawMessage `json:"facilities"`
}

type CreateRoomRow struct {
	ID         uuid.UUID             `json:"id"`
	PropertyID uuid.UUID             `json:"property_id"`
	RoomTypeID uuid.NullUUID         `json:"room_type_id"`
	Number     string                `json:"number"`
	Floor      sql.NullInt32         `json:"floor"`
	Status     string                `json:"status"`
	GridX      sql.NullInt32         `json:"grid_x"`
	GridY      sql.NullInt32         `json:"grid_y"`
	Facilities pqtype.NullRawMessage `json:"facilities"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (CreateRoomRow, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.Number,
		arg.Floor,
		arg.Status,
		arg.GridX,
		arg.GridY,
		arg.Facilities,
	)
	var i CreateRoomRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.Number,
		&i.Floor,
		&i.Status,
		&i.GridX,
		&i.GridY,
		&i.Facilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT r.id, r.property_id, r.room_type_id, r.number, r.floor, r.status,
       r.grid_x, r.grid_y, r.facilities, r.created_at, r.updated_at,
       rt.name AS room_type_name, rt.monthly_price
FROM rooms r
LEFT JOIN room_types rt ON rt.id = r.room_type_id
WHERE r.id = $1
`

type GetRoomRow struct {
	ID           uuid.UUID             `json:"id"`
	PropertyID   uuid.UUID             `json:"property_id"`
	RoomTypeID   uuid.NullUUID         `json:"room_type_id"`
	Number       string                `json:"number"`
	Floor        sql.NullInt32         `json:"floor"`
	Status       string                `json:"status"`
	GridX        sql.NullInt32         `json:"grid_x"`
	GridY        sql.NullInt32         `json:"grid_y"`
	Facilities   pqtype.NullRawMessage `json:"facilities"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
	RoomTypeName sql.NullString        `json:"room_type_name"`
	MonthlyPrice sql.NullString        `json:"monthly_price"`
}

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (GetRoomRow, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i GetRoomRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.Number,
		&i.Floor,
		&i.Status,
		&i.GridX,
		&i.GridY,
		&i.Facilities,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoomTypeName,
		&i.MonthlyPrice,
	)
	return i, err
}

const getRoomHistory = `-- name: GetRoomHistory :many
SELECT c.id, c.tenant_id, c.room_id, c.property_id, c.start_date, c.end_date,
       c.monthly_price, c.deposit_amount, c.deposit_refunded, c.status,
       c.file_url, c.created_at, c.updated_at,
       p.full_name AS tenant_name
FROM contracts c
JOIN tenants t ON t.id = c.tenant_id
JOIN profiles p ON p.id = t.id
WHERE c.room_id = $1
ORDER BY c.start_date DESC
`

type GetRoomHistoryRow struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	RoomID          uuid.UUID      `json:"room_id"`
	PropertyID      uuid.UUID      `json:"property_id"`
	StartDate       time.Time      `json:"start_date"`
	EndDate         time.Time      `json:"end_date"`
	MonthlyPrice    string         `json:"monthly_price"`
	DepositAmount   sql.NullString `json:"deposit_amount"`
	DepositRefunded sql.NullString `json:"deposit_refunded"`
	Status          string         `json:"status"`
	FileUrl         sql.NullString `json:"file_url"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	TenantName      string         `json:"tenant_name"`
}

func (q *Queries) GetRoomHistory(ctx context.Context, roomID uuid.UUID) ([]GetRoomHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomHistory, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomHistoryRow{}
	for rows.Next() {
		var i GetRoomHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.PropertyID,
			&i.StartDate,
			&i.EndDate,
			&i.MonthlyPrice,
			&i.DepositAmount,
			&i.DepositRefunded,
			&i.Status,
			&i.FileUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByProperty = `-- name: ListRoomsByProperty :many
SELECT r.id, r.property_id, r.room_type_id, r.number, r.floor, r.status,
       r.grid_x, r.grid_y, r.facilities, r.created_at, r.updated_at,
       rt.name AS room_type_name, rt.monthly_price
FROM rooms r
LEFT JOIN room_types rt ON rt.id = r.room_type_id
WHERE r.property_id = $1
ORDER BY r.number ASC
`

type ListRoomsByPropertyRow struct {
	ID           uuid.UUID             `json:"id"`
	PropertyID   uuid.UUID             `json:"property_id"`
	RoomTypeID   uuid.NullUUID         `json:"room_type_id"`
	Number       string                `json:"number"`
	Floor        sql.NullInt32         `json:"floor"`
	Status       string                `json:"status"`
	GridX        sql.NullInt32         `json:"grid_x"`
	GridY        sql.NullInt32         `json:"grid_y"`
	Facilities   pqtype.NullRawMessage `json:"facilities"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
	RoomTypeName sql.NullString        `json:"room_type_name"`
	MonthlyPrice sql.NullString        `json:"monthly_price"`
}

func (q *Queries) ListRoomsByProperty(ctx context.Context, propertyID uuid.UUID) ([]ListRoomsByPropertyRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsByPropertyRow{}
	for rows.Next() {
		var i ListRoomsByPropertyRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomTypeID,
			&i.Number,
			&i.Floor,
			&i.Status,
			&i.GridX,
			&i.GridY,
			&i.Facilities,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoomTypeName,
			&i.MonthlyPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET room_type_id = $2,
    number       = $3,
    floor        = $4,
    status       = $5,
    grid_x       = $6,
    grid_y       = $7,
    facilities   = $8,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, property_id, room_type_id, number, floor, status, grid_x, grid_y, facilities, created_at, updated_at
`

type UpdateRoomParams struct {
	ID         uuid.UUID             `json:"id"`
	RoomTypeID uuid.NullUUID         `json:"room_type_id"`
	Number     string                `json:"number"`
	Floor      sql.NullInt32         `json:"floor"`
	Status     string                `json:"status"`
	GridX      sql.NullInt32         `json:"grid_x"`
	GridY      sql.NullInt32         `json:"grid_y"`
	Facilities pqtype.NullRawMessage `json:"facilities"`
}

type UpdateRoomRow struct {
	ID         uuid.UUID             `json:"id"`
	PropertyID uuid.UUID             `json:"property_id"`
	RoomTypeID uuid.NullUUID         `json:"room_type_id"`
	Number     string                `json:"number"`
	Floor      sql.NullInt32         `json:"floor"`
	Status     string                `json:"status"`
	GridX      sql.NullInt32         `json:"grid_x"`
	GridY      sql.NullInt32         `json:"grid_y"`
	Facilities pqtype.NullRawMessage `json:"facilities"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (UpdateRoomRow, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.ID,
		arg.RoomTypeID,
		arg.Number,
		arg.Floor,
		arg.Status,
		arg.GridX,
		arg.GridY,
		arg.Facilities,
	)
	var i UpdateRoomRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.Number,
		&i.Floor,
		&i.Status,
		&i.GridX,
		&i.GridY,
		&i.Facilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoomLayout = `-- name: UpdateRoomLayout :exec
UPDATE rooms
SET grid_x     = $2,
    grid_y     = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRoomLayoutParams struct {
	ID    uuid.UUID     `json:"id"`
	GridX sql.NullInt32 `json:"grid_x"`
	GridY sql.NullInt32 `json:"grid_y"`
}

func (q *Queries) UpdateRoomLayout(ctx context.Context, arg UpdateRoomLayoutParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomLayout, arg.ID, arg.GridX, arg.GridY)
	return err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, property_id, room_type_id, number, floor, status, grid_x, grid_y, facilities, created_at, updated_at
`

type UpdateRoomStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

type UpdateRoomStatusRow struct {
	ID         uuid.UUID             `json:"id"`
	PropertyID uuid.UUID             `json:"property_id"`
	RoomTypeID uuid.NullUUID         `json:"room_type_id"`
	Number     string                `json:"number"`
	Floor      sql.NullInt32         `json:"floor"`
	Status     string                `json:"status"`
	GridX      sql.NullInt32         `json:"grid_x"`
	GridY      sql.NullInt32         `json:"grid_y"`
	Facilities pqtype.NullRawMessage `json:"facilities"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (UpdateRoomStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateRoomStatus, arg.ID, arg.Status)
	var i UpdateRoomStatusRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.Number,
		&i.Floor,
		&i.Status,
		&i.GridX,
		&i.GridY,
		&i.Facilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
