// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getPropertySettings = `-- name: GetPropertySettings :one
SELECT id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account,
       due_date_day, grace_period_days, penalty_type, penalty_amount,
       created_at, updated_at
FROM properties
WHERE id = $1
  AND archived_at IS NULL
`

type GetPropertySettingsRow struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	Address         string         `json:"address"`
	City            sql.NullString `json:"city"`
	LogoUrl         sql.NullString `json:"logo_url"`
	Phone           sql.NullString `json:"phone"`
	BankName        sql.NullString `json:"bank_name"`
	BankAccount     sql.NullString `json:"bank_account"`
	DueDateDay      sql.NullInt32  `json:"due_date_day"`
	GracePeriodDays sql.NullInt32  `json:"grace_period_days"`
	PenaltyType     sql.NullString `json:"penalty_type"`
	PenaltyAmount   sql.NullString `json:"penalty_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetPropertySettings(ctx context.Context, id uuid.UUID) (GetPropertySettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getPropertySettings, id)
	var i GetPropertySettingsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.DueDateDay,
		&i.GracePeriodDays,
		&i.PenaltyType,
		&i.PenaltyAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingsByOwner = `-- name: GetSettingsByOwner :one
SELECT id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account,
       due_date_day, grace_period_days, penalty_type, penalty_amount,
       created_at, updated_at
FROM properties
WHERE owner_id = $1
  AND archived_at IS NULL
ORDER BY created_at ASC
LIMIT 1
`

type GetSettingsByOwnerRow struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	Address         string         `json:"address"`
	City            sql.NullString `json:"city"`
	LogoUrl         sql.NullString `json:"logo_url"`
	Phone           sql.NullString `json:"phone"`
	BankName        sql.NullString `json:"bank_name"`
	BankAccount     sql.NullString `json:"bank_account"`
	DueDateDay      sql.NullInt32  `json:"due_date_day"`
	GracePeriodDays sql.NullInt32  `json:"grace_period_days"`
	PenaltyType     sql.NullString `json:"penalty_type"`
	PenaltyAmount   sql.NullString `json:"penalty_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetSettingsByOwner(ctx context.Context, ownerID uuid.UUID) (GetSettingsByOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByOwner, ownerID)
	var i GetSettingsByOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.DueDateDay,
		&i.GracePeriodDays,
		&i.PenaltyType,
		&i.PenaltyAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillsByOwnerForExport = `-- name: ListBillsByOwnerForExport :many
SELECT b.id, b.tenant_id, b.property_id, b.room_id, b.period_month, b.period_year,
       b.base_amount, b.utility_amount, b.penalty_amount, b.total_amount,
       b.due_date, b.status, b.created_at
FROM bills b
JOIN properties p ON p.id = b.property_id
WHERE p.owner_id = $1
  AND p.archived_at IS NULL
ORDER BY b.property_id, b.period_year DESC, b.period_month DESC
`

type ListBillsByOwnerForExportRow struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	PropertyID    uuid.UUID      `json:"property_id"`
	RoomID        uuid.UUID      `json:"room_id"`
	PeriodMonth   int32          `json:"period_month"`
	PeriodYear    int32          `json:"period_year"`
	BaseAmount    string         `json:"base_amount"`
	UtilityAmount sql.NullString `json:"utility_amount"`
	PenaltyAmount sql.NullString `json:"penalty_amount"`
	TotalAmount   sql.NullString `json:"total_amount"`
	DueDate       time.Time      `json:"due_date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListBillsByOwnerForExport(ctx context.Context, ownerID uuid.UUID) ([]ListBillsByOwnerForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listBillsByOwnerForExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillsByOwnerForExportRow{}
	for rows.Next() {
		var i ListBillsByOwnerForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.RoomID,
			&i.PeriodMonth,
			&i.PeriodYear,
			&i.BaseAmount,
			&i.UtilityAmount,
			&i.PenaltyAmount,
			&i.TotalAmount,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsByOwnerForExport = `-- name: ListContractsByOwnerForExport :many
SELECT c.id, c.tenant_id, c.room_id, c.property_id, c.start_date, c.end_date,
       c.monthly_price, c.deposit_amount, c.deposit_refunded, c.status, c.created_at
FROM contracts c
JOIN properties p ON p.id = c.property_id
WHERE p.owner_id = $1
  AND p.archived_at IS NULL
ORDER BY c.property_id, c.start_date DESC
`

type ListContractsByOwnerForExportRow struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	RoomID          uuid.UUID      `json:"room_id"`
	PropertyID      uuid.UUID      `json:"property_id"`
	StartDate       time.Time      `json:"start_date"`
	EndDate         time.Time      `json:"end_date"`
	MonthlyPrice    string         `json:"monthly_price"`
	DepositAmount   sql.NullString `json:"deposit_amount"`
	DepositRefunded sql.NullString `json:"deposit_refunded"`
	Status          string         `json:"status"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListContractsByOwnerForExport(ctx context.Context, ownerID uuid.UUID) ([]ListContractsByOwnerForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listContractsByOwnerForExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractsByOwnerForExportRow{}
	for rows.Next() {
		var i ListContractsByOwnerForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.PropertyID,
			&i.StartDate,
			&i.EndDate,
			&i.MonthlyPrice,
			&i.DepositAmount,
			&i.DepositRefunded,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOwnerForExport = `-- name: ListPaymentsByOwnerForExport :many
SELECT pay.id, pay.bill_id, pay.tenant_id, pay.amount, pay.status,
       pay.confirmed_at, pay.created_at
FROM payments pay
JOIN bills b ON b.id = pay.bill_id
JOIN properties p ON p.id = b.property_id
WHERE p.owner_id = $1
  AND p.archived_at IS NULL
ORDER BY pay.created_at DESC
`

type ListPaymentsByOwnerForExportRow struct {
	ID          uuid.UUID    `json:"id"`
	BillID      uuid.UUID    `json:"bill_id"`
	TenantID    uuid.UUID    `json:"tenant_id"`
	Amount      string       `json:"amount"`
	Status      string       `json:"status"`
	ConfirmedAt sql.NullTime `json:"confirmed_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

func (q *Queries) ListPaymentsByOwnerForExport(ctx context.Context, ownerID uuid.UUID) ([]ListPaymentsByOwnerForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByOwnerForExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByOwnerForExportRow{}
	for rows.Next() {
		var i ListPaymentsByOwnerForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.TenantID,
			&i.Amount,
			&i.Status,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesByOwnerForExport = `-- name: ListPropertiesByOwnerForExport :many
SELECT id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account,
       due_date_day, grace_period_days, penalty_type, penalty_amount,
       created_at, updated_at
FROM properties
WHERE owner_id = $1
  AND archived_at IS NULL
ORDER BY created_at ASC
`

type ListPropertiesByOwnerForExportRow struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	Address         string         `json:"address"`
	City            sql.NullString `json:"city"`
	LogoUrl         sql.NullString `json:"logo_url"`
	Phone           sql.NullString `json:"phone"`
	BankName        sql.NullString `json:"bank_name"`
	BankAccount     sql.NullString `json:"bank_account"`
	DueDateDay      sql.NullInt32  `json:"due_date_day"`
	GracePeriodDays sql.NullInt32  `json:"grace_period_days"`
	PenaltyType     sql.NullString `json:"penalty_type"`
	PenaltyAmount   sql.NullString `json:"penalty_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListPropertiesByOwnerForExport(ctx context.Context, ownerID uuid.UUID) ([]ListPropertiesByOwnerForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesByOwnerForExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesByOwnerForExportRow{}
	for rows.Next() {
		var i ListPropertiesByOwnerForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.LogoUrl,
			&i.Phone,
			&i.BankName,
			&i.BankAccount,
			&i.DueDateDay,
			&i.GracePeriodDays,
			&i.PenaltyType,
			&i.PenaltyAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByOwnerForExport = `-- name: ListRoomsByOwnerForExport :many
SELECT r.id, r.property_id, r.number, r.floor, r.status, r.created_at
FROM rooms r
JOIN properties p ON p.id = r.property_id
WHERE p.owner_id = $1
  AND r.archived_at IS NULL
  AND p.archived_at IS NULL
ORDER BY r.property_id, r.number
`

type ListRoomsByOwnerForExportRow struct {
	ID         uuid.UUID     `json:"id"`
	PropertyID uuid.UUID     `json:"property_id"`
	Number     string        `json:"number"`
	Floor      sql.NullInt32 `json:"floor"`
	Status     string        `json:"status"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

func (q *Queries) ListRoomsByOwnerForExport(ctx context.Context, ownerID uuid.UUID) ([]ListRoomsByOwnerForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsByOwnerForExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsByOwnerForExportRow{}
	for rows.Next() {
		var i ListRoomsByOwnerForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Number,
			&i.Floor,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsByOwnerForExport = `-- name: ListTenantsByOwnerForExport :many
SELECT t.id, t.property_id, t.room_id, t.ktp_number, t.occupation,
       t.is_blacklisted, t.created_at,
       pr.full_name, pr.phone
FROM tenants t
JOIN profiles pr ON pr.id = t.id
JOIN properties p ON p.id = t.property_id
WHERE p.owner_id = $1
  AND p.archived_at IS NULL
ORDER BY t.property_id, pr.full_name
`

type ListTenantsByOwnerForExportRow struct {
	ID            uuid.UUID      `json:"id"`
	PropertyID    uuid.NullUUID  `json:"property_id"`
	RoomID        uuid.NullUUID  `json:"room_id"`
	KtpNumber     sql.NullString `json:"ktp_number"`
	Occupation    sql.NullString `json:"occupation"`
	IsBlacklisted sql.NullBool   `json:"is_blacklisted"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	FullName      string         `json:"full_name"`
	Phone         sql.NullString `json:"phone"`
}

func (q *Queries) ListTenantsByOwnerForExport(ctx context.Context, ownerID uuid.UUID) ([]ListTenantsByOwnerForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsByOwnerForExport, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsByOwnerForExportRow{}
	for rows.Next() {
		var i ListTenantsByOwnerForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomID,
			&i.KtpNumber,
			&i.Occupation,
			&i.IsBlacklisted,
			&i.CreatedAt,
			&i.FullName,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBillingSettings = `-- name: UpdateBillingSettings :one
UPDATE properties
SET due_date_day      = $2,
    grace_period_days = $3,
    penalty_type      = $4,
    penalty_amount    = $5,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account,
          due_date_day, grace_period_days, penalty_type, penalty_amount,
          created_at, updated_at
`

type UpdateBillingSettingsParams struct {
	ID              uuid.UUID      `json:"id"`
	DueDateDay      sql.NullInt32  `json:"due_date_day"`
	GracePeriodDays sql.NullInt32  `json:"grace_period_days"`
	PenaltyType     sql.NullString `json:"penalty_type"`
	PenaltyAmount   sql.NullString `json:"penalty_amount"`
}

type UpdateBillingSettingsRow struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	Address         string         `json:"address"`
	City            sql.NullString `json:"city"`
	LogoUrl         sql.NullString `json:"logo_url"`
	Phone           sql.NullString `json:"phone"`
	BankName        sql.NullString `json:"bank_name"`
	BankAccount     sql.NullString `json:"bank_account"`
	DueDateDay      sql.NullInt32  `json:"due_date_day"`
	GracePeriodDays sql.NullInt32  `json:"grace_period_days"`
	PenaltyType     sql.NullString `json:"penalty_type"`
	PenaltyAmount   sql.NullString `json:"penalty_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateBillingSettings(ctx context.Context, arg UpdateBillingSettingsParams) (UpdateBillingSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, updateBillingSettings,
		arg.ID,
		arg.DueDateDay,
		arg.GracePeriodDays,
		arg.PenaltyType,
		arg.PenaltyAmount,
	)
	var i UpdateBillingSettingsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.DueDateDay,
		&i.GracePeriodDays,
		&i.PenaltyType,
		&i.PenaltyAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileSettings = `-- name: UpdateProfileSettings :one
UPDATE properties
SET name         = $2,
    address      = $3,
    city         = $4,
    logo_url     = $5,
    phone        = $6,
    bank_name    = $7,
    bank_account = $8,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, owner_id, name, address, city, logo_url, phone, bank_name, bank_account,
          due_date_day, grace_period_days, penalty_type, penalty_amount,
          created_at, updated_at
`

type UpdateProfileSettingsParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        sql.NullString `json:"city"`
	LogoUrl     sql.NullString `json:"logo_url"`
	Phone       sql.NullString `json:"phone"`
	BankName    sql.NullString `json:"bank_name"`
	BankAccount sql.NullString `json:"bank_account"`
}

type UpdateProfileSettingsRow struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	Address         string         `json:"address"`
	City            sql.NullString `json:"city"`
	LogoUrl         sql.NullString `json:"logo_url"`
	Phone           sql.NullString `json:"phone"`
	BankName        sql.NullString `json:"bank_name"`
	BankAccount     sql.NullString `json:"bank_account"`
	DueDateDay      sql.NullInt32  `json:"due_date_day"`
	GracePeriodDays sql.NullInt32  `json:"grace_period_days"`
	PenaltyType     sql.NullString `json:"penalty_type"`
	PenaltyAmount   sql.NullString `json:"penalty_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateProfileSettings(ctx context.Context, arg UpdateProfileSettingsParams) (UpdateProfileSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, updateProfileSettings,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.LogoUrl,
		arg.Phone,
		arg.BankName,
		arg.BankAccount,
	)
	var i UpdateProfileSettingsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Phone,
		&i.BankName,
		&i.BankAccount,
		&i.DueDateDay,
		&i.GracePeriodDays,
		&i.PenaltyType,
		&i.PenaltyAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
