// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: staff_permissions.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createStaffPermissions = `-- name: CreateStaffPermissions :one
INSERT INTO staff_permissions (staff_id, owner_id, modules)
VALUES ($1, $2, $3)
RETURNING id, staff_id, owner_id, modules, created_at
`

type CreateStaffPermissionsParams struct {
	StaffID uuid.UUID       `json:"staff_id"`
	OwnerID uuid.UUID       `json:"owner_id"`
	Modules json.RawMessage `json:"modules"`
}

func (q *Queries) CreateStaffPermissions(ctx context.Context, arg CreateStaffPermissionsParams) (StaffPermission, error) {
	row := q.db.QueryRowContext(ctx, createStaffPermissions, arg.StaffID, arg.OwnerID, arg.Modules)
	var i StaffPermission
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.OwnerID,
		&i.Modules,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStaffPermissions = `-- name: DeleteStaffPermissions :exec
DELETE FROM staff_permissions
WHERE staff_id = $1
  AND owner_id = $2
`

type DeleteStaffPermissionsParams struct {
	StaffID uuid.UUID `json:"staff_id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteStaffPermissions(ctx context.Context, arg DeleteStaffPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteStaffPermissions, arg.StaffID, arg.OwnerID)
	return err
}

const getStaffPermissions = `-- name: GetStaffPermissions :one
SELECT id, staff_id, owner_id, modules, created_at
FROM staff_permissions
WHERE staff_id = $1
  AND owner_id = $2
`

type GetStaffPermissionsParams struct {
	StaffID uuid.UUID `json:"staff_id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetStaffPermissions(ctx context.Context, arg GetStaffPermissionsParams) (StaffPermission, error) {
	row := q.db.QueryRowContext(ctx, getStaffPermissions, arg.StaffID, arg.OwnerID)
	var i StaffPermission
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.OwnerID,
		&i.Modules,
		&i.CreatedAt,
	)
	return i, err
}

const listStaffByOwner = `-- name: ListStaffByOwner :many
SELECT sp.id, sp.staff_id, sp.owner_id, sp.modules, sp.created_at,
       p.full_name, p.avatar_url, p.phone, p.role
FROM staff_permissions sp
JOIN profiles p ON p.id = sp.staff_id
WHERE sp.owner_id = $1
ORDER BY p.full_name ASC
`

type ListStaffByOwnerRow struct {
	ID        uuid.UUID       `json:"id"`
	StaffID   uuid.UUID       `json:"staff_id"`
	OwnerID   uuid.UUID       `json:"owner_id"`
	Modules   json.RawMessage `json:"modules"`
	CreatedAt sql.NullTime    `json:"created_at"`
	FullName  string          `json:"full_name"`
	AvatarUrl sql.NullString  `json:"avatar_url"`
	Phone     sql.NullString  `json:"phone"`
	Role      string          `json:"role"`
}

func (q *Queries) ListStaffByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListStaffByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaffByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffByOwnerRow{}
	for rows.Next() {
		var i ListStaffByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.OwnerID,
			&i.Modules,
			&i.CreatedAt,
			&i.FullName,
			&i.AvatarUrl,
			&i.Phone,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
