// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

// ListTenantsRow is the return type for ListTenants.
type ListTenantsRow struct {
	ID              uuid.UUID      `json:"id"`
	PropertyID      uuid.NullUUID  `json:"property_id"`
	RoomID          uuid.NullUUID  `json:"room_id"`
	KtpNumber       sql.NullString `json:"ktp_number"`
	KtpScanUrl      sql.NullString `json:"ktp_scan_url"`
	Occupation      sql.NullString `json:"occupation"`
	EmergencyName   sql.NullString `json:"emergency_name"`
	EmergencyPhone  sql.NullString `json:"emergency_phone"`
	IsBlacklisted   sql.NullBool   `json:"is_blacklisted"`
	BlacklistReason sql.NullString `json:"blacklist_reason"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	FullName        string         `json:"full_name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	Phone           sql.NullString `json:"phone"`
	Role            string         `json:"role"`
}

const listTenants = `-- name: ListTenants :many
SELECT t.id, t.property_id, t.room_id, t.ktp_number, t.ktp_scan_url,
       t.occupation, t.emergency_name, t.emergency_phone,
       t.is_blacklisted, t.blacklist_reason, t.created_at, t.updated_at,
       p.full_name, p.avatar_url, p.phone, p.role
FROM tenants t
JOIN profiles p ON p.id = t.id
WHERE t.property_id = $1
ORDER BY p.full_name ASC
`

func (q *Queries) ListTenants(ctx context.Context, propertyID uuid.NullUUID) ([]ListTenantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenants, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsRow
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomID,
			&i.KtpNumber,
			&i.KtpScanUrl,
			&i.Occupation,
			&i.EmergencyName,
			&i.EmergencyPhone,
			&i.IsBlacklisted,
			&i.BlacklistReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.AvatarUrl,
			&i.Phone,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// GetTenantRow is the return type for GetTenant.
type GetTenantRow struct {
	ID              uuid.UUID      `json:"id"`
	PropertyID      uuid.NullUUID  `json:"property_id"`
	RoomID          uuid.NullUUID  `json:"room_id"`
	KtpNumber       sql.NullString `json:"ktp_number"`
	KtpScanUrl      sql.NullString `json:"ktp_scan_url"`
	Occupation      sql.NullString `json:"occupation"`
	EmergencyName   sql.NullString `json:"emergency_name"`
	EmergencyPhone  sql.NullString `json:"emergency_phone"`
	IsBlacklisted   sql.NullBool   `json:"is_blacklisted"`
	BlacklistReason sql.NullString `json:"blacklist_reason"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	FullName        string         `json:"full_name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	Phone           sql.NullString `json:"phone"`
	Role            string         `json:"role"`
}

const getTenant = `-- name: GetTenant :one
SELECT t.id, t.property_id, t.room_id, t.ktp_number, t.ktp_scan_url,
       t.occupation, t.emergency_name, t.emergency_phone,
       t.is_blacklisted, t.blacklist_reason, t.created_at, t.updated_at,
       p.full_name, p.avatar_url, p.phone, p.role
FROM tenants t
JOIN profiles p ON p.id = t.id
WHERE t.id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (GetTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i GetTenantRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomID,
		&i.KtpNumber,
		&i.KtpScanUrl,
		&i.Occupation,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.IsBlacklisted,
		&i.BlacklistReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Role,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, property_id, room_id, ktp_number, ktp_scan_url, occupation, emergency_name, emergency_phone)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, property_id, room_id, ktp_number, ktp_scan_url, occupation, emergency_name, emergency_phone, is_blacklisted, blacklist_reason, created_at, updated_at
`

type CreateTenantParams struct {
	ID             uuid.UUID   `json:"id"`
	PropertyID     interface{} `json:"property_id"`
	RoomID         interface{} `json:"room_id"`
	KtpNumber      interface{} `json:"ktp_number"`
	KtpScanUrl     interface{} `json:"ktp_scan_url"`
	Occupation     interface{} `json:"occupation"`
	EmergencyName  interface{} `json:"emergency_name"`
	EmergencyPhone interface{} `json:"emergency_phone"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.ID,
		arg.PropertyID,
		arg.RoomID,
		arg.KtpNumber,
		arg.KtpScanUrl,
		arg.Occupation,
		arg.EmergencyName,
		arg.EmergencyPhone,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomID,
		&i.KtpNumber,
		&i.KtpScanUrl,
		&i.Occupation,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.IsBlacklisted,
		&i.BlacklistReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET property_id     = $2,
    room_id         = $3,
    ktp_number      = $4,
    ktp_scan_url    = $5,
    occupation      = $6,
    emergency_name  = $7,
    emergency_phone = $8,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, property_id, room_id, ktp_number, ktp_scan_url, occupation, emergency_name, emergency_phone, is_blacklisted, blacklist_reason, created_at, updated_at
`

type UpdateTenantParams struct {
	ID             uuid.UUID   `json:"id"`
	PropertyID     interface{} `json:"property_id"`
	RoomID         interface{} `json:"room_id"`
	KtpNumber      interface{} `json:"ktp_number"`
	KtpScanUrl     interface{} `json:"ktp_scan_url"`
	Occupation     interface{} `json:"occupation"`
	EmergencyName  interface{} `json:"emergency_name"`
	EmergencyPhone interface{} `json:"emergency_phone"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenant,
		arg.ID,
		arg.PropertyID,
		arg.RoomID,
		arg.KtpNumber,
		arg.KtpScanUrl,
		arg.Occupation,
		arg.EmergencyName,
		arg.EmergencyPhone,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomID,
		&i.KtpNumber,
		&i.KtpScanUrl,
		&i.Occupation,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.IsBlacklisted,
		&i.BlacklistReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const blacklistTenant = `-- name: BlacklistTenant :one
UPDATE tenants
SET is_blacklisted   = TRUE,
    blacklist_reason = $2,
    updated_at       = NOW()
WHERE id = $1
RETURNING id, property_id, room_id, ktp_number, ktp_scan_url, occupation, emergency_name, emergency_phone, is_blacklisted, blacklist_reason, created_at, updated_at
`

type BlacklistTenantParams struct {
	ID              uuid.UUID   `json:"id"`
	BlacklistReason interface{} `json:"blacklist_reason"`
}

func (q *Queries) BlacklistTenant(ctx context.Context, arg BlacklistTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, blacklistTenant, arg.ID, arg.BlacklistReason)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.RoomID,
		&i.KtpNumber,
		&i.KtpScanUrl,
		&i.Occupation,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.IsBlacklisted,
		&i.BlacklistReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
