// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tickets.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (tenant_id, property_id, room_id, title, description, priority, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, property_id, room_id, title, description, priority, status, resolution, created_at, updated_at
`

type CreateTicketParams struct {
	TenantID    uuid.UUID     `json:"tenant_id"`
	PropertyID  uuid.UUID     `json:"property_id"`
	RoomID      uuid.NullUUID `json:"room_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Priority    string        `json:"priority"`
	Status      string        `json:"status"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.TenantID,
		arg.PropertyID,
		arg.RoomID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, tenant_id, property_id, room_id, title, description,
       priority, status, resolution, created_at, updated_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, tenant_id, property_id, room_id, title, description,
       priority, status, resolution, created_at, updated_at
FROM tickets
WHERE property_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTickets(ctx context.Context, propertyID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET priority   = $2,
    status     = $3,
    resolution = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, property_id, room_id, title, description, priority, status, resolution, created_at, updated_at
`

type UpdateTicketParams struct {
	ID         uuid.UUID      `json:"id"`
	Priority   string         `json:"priority"`
	Status     string         `json:"status"`
	Resolution sql.NullString `json:"resolution"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.ID,
		arg.Priority,
		arg.Status,
		arg.Resolution,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
