// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ticket_attachments.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createTicketAttachment = `-- name: CreateTicketAttachment :one
INSERT INTO ticket_attachments (ticket_id, url)
VALUES ($1, $2)
RETURNING id, ticket_id, url, created_at
`

type CreateTicketAttachmentParams struct {
	TicketID uuid.UUID `json:"ticket_id"`
	Url      string    `json:"url"`
}

func (q *Queries) CreateTicketAttachment(ctx context.Context, arg CreateTicketAttachmentParams) (TicketAttachment, error) {
	row := q.db.QueryRowContext(ctx, createTicketAttachment, arg.TicketID, arg.Url)
	var i TicketAttachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketAttachments = `-- name: ListTicketAttachments :many
SELECT id, ticket_id, url, created_at
FROM ticket_attachments
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTicketAttachments(ctx context.Context, ticketID uuid.UUID) ([]TicketAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listTicketAttachments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAttachment
	for rows.Next() {
		var i TicketAttachment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
