// Package service contains business logic for the KosKu API.
package service

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"fmt"
	"strings"
	"time"
)

// buildMinimalDOCX constructs a minimal but valid Office Open XML (.docx) file
// from plain text content. It creates the required ZIP structure with the
// necessary XML parts without relying on any external DOCX library.
func buildMinimalDOCX(content string) ([]byte, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	// [Content_Types].xml
	if err := addZipFile(zw, "[Content_Types].xml", contentTypesXML()); err != nil {
		return nil, fmt.Errorf("docx: write content types: %w", err)
	}

	// _rels/.rels
	if err := addZipFile(zw, "_rels/.rels", rootRelsXML()); err != nil {
		return nil, fmt.Errorf("docx: write root rels: %w", err)
	}

	// word/_rels/document.xml.rels
	if err := addZipFile(zw, "word/_rels/document.xml.rels", documentRelsXML()); err != nil {
		return nil, fmt.Errorf("docx: write document rels: %w", err)
	}

	// word/document.xml
	docXML := buildDocumentXML(content)
	if err := addZipFile(zw, "word/document.xml", docXML); err != nil {
		return nil, fmt.Errorf("docx: write document xml: %w", err)
	}

	// word/settings.xml
	if err := addZipFile(zw, "word/settings.xml", settingsXML()); err != nil {
		return nil, fmt.Errorf("docx: write settings: %w", err)
	}

	if err := zw.Close(); err != nil {
		return nil, fmt.Errorf("docx: close zip: %w", err)
	}

	return buf.Bytes(), nil
}

// addZipFile adds a file with the given name and content to the ZIP writer.
func addZipFile(zw *zip.Writer, name, content string) error {
	w, err := zw.Create(name)
	if err != nil {
		return err
	}
	_, err = w.Write([]byte(content))
	return err
}

// contentTypesXML returns the [Content_Types].xml content.
func contentTypesXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>
</Types>`
}

// rootRelsXML returns the _rels/.rels content.
func rootRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`
}

// documentRelsXML returns the word/_rels/document.xml.rels content.
func documentRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>
</Relationships>`
}

// settingsXML returns the word/settings.xml content.
func settingsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:defaultTabStop w:val="720"/>
</w:settings>`
}

// buildDocumentXML constructs the word/document.xml content from plain text.
// Each newline in the content becomes a new paragraph.
func buildDocumentXML(content string) string {
	lines := strings.Split(content, "\n")

	var paragraphs strings.Builder
	for _, line := range lines {
		// Escape XML special characters.
		escaped := xmlEscape(line)
		fmt.Fprintf(&paragraphs,
			`<w:p><w:r><w:t xml:space="preserve">%s</w:t></w:r></w:p>`,
			escaped,
		)
	}

	// Add a footer paragraph with generation timestamp.
	timestamp := xmlEscape("Generated by KosKu on " + time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(&paragraphs,
		`<w:p><w:pPr><w:jc w:val="right"/></w:pPr><w:r><w:rPr><w:i/><w:sz w:val="18"/></w:rPr><w:t>%s</w:t></w:r></w:p>`,
		timestamp,
	)

	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"
            xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
    %s
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
    </w:sectPr>
  </w:body>
</w:document>`, paragraphs.String())
}

// xmlEscape escapes the five XML special characters in a string.
func xmlEscape(s string) string {
	// Use the standard library's xml.EscapeText for correctness.
	var buf bytes.Buffer
	_ = xml.EscapeText(&buf, []byte(s))
	return buf.String()
}
